# Generated by Django 3.1.2 on 2021-05-01 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('totalBalance', models.DecimalField(decimal_places=2, max_digits=100)),
                ('photoUrl', models.URLField(null=True)),
                ('phoneNumber', models.BigIntegerField()),
                ('group', models.ManyToManyField(to='spay.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('totalAmount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('friends', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to='spay.user')),
                ('paidBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_by', to='spay.user')),
            ],
        ),
    ]
