# Generated by Django 3.2 on 2021-05-01 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('emailAddress', models.EmailField(max_length=254)),
                ('phoneNumber', models.BigIntegerField()),
                ('totalBalance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('users', models.ManyToManyField(to='spay.User')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('amount', models.IntegerField()),
                ('paidBy', models.ManyToManyField(to='spay.User')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='spay.user')),
            ],
        ),
    ]
