# Generated by Django 3.2 on 2021-05-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='group',
            field=models.ManyToManyField(related_name='group', to='spay.Group'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='paidBy',
            field=models.ManyToManyField(related_name='paidBy', to='spay.User'),
        ),
        migrations.RemoveField(
            model_name='expense',
            name='users',
        ),
        migrations.AddField(
            model_name='expense',
            name='users',
            field=models.ManyToManyField(related_name='users', to='spay.User'),
        ),
    ]
