# Generated by Django 3.1.2 on 2021-05-01 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spay', '0004_auto_20210501_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='spay.group'),
        ),
    ]
