# Generated by Django 3.2 on 2021-05-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spay', '0004_auto_20210501_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.AddField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(to='spay.User'),
        ),
    ]
