# Generated by Django 3.2 on 2021-05-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spay', '0005_auto_20210501_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='totalBalance',
            field=models.FloatField(),
        ),
    ]
