# Generated by Django 3.1.2 on 2021-05-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spay', '0005_expense_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='group',
        ),
        migrations.AddField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(to='spay.User'),
        ),
    ]
