# Generated by Django 3.1.2 on 2021-05-13 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spay', '0006_auto_20210501_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='authentic_user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
