# Generated by Django 3.1.2 on 2021-05-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spay', '0008_auto_20210514_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='amount_debit',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='amount_owed',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True),
        ),
    ]
